dummiebot:
  # Publish joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  mobile_base_controller:
    type: diff_drive_controller/DiffDriveController
    left_wheel: left_wheel_hinge
    right_wheel: right_wheel_hinge
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    cmd_vel_timeout: 0.25
    wheel_separation: ${chassis_width}
    wheel_radius: ${wheel_radius}

  gazebo_ros_control:
    pid_gains:
      left_wheel_hinge: {p: 100.0, i: 0.0, d: 0.0}
      right_wheel_hinge: {p: 100.0, i: 0.0, d: 0.0}

  #Rotation Controllers
  z_rotation_controller:
    type: effort_controllers/JointPositionController
    joint: chassis_body_joint
    pid: {p: 100.0, i: 0.1, d: 10.0}
  y_rotation_controller:
    type: effort_controllers/JointPositionController
    joint: body_joint_body
    pid: {p: 100.0, i: 0.1, d: 10.0}
