<robot name="dummiebot" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Macros for inertia of different shapes -->
  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertia  ixx="${m*(3*r*r+h*h)/12}" ixy="0" ixz="0"
              iyy="${m*(3*r*r+h*h)/12}" iyz="0"
              izz="${m*r*r/2}"
    />
  </xacro:macro>

  <xacro:macro name="box_inertia" params="m x y z">
    <inertia  ixx="${m*(y*y+z*z)/12}" ixy="0" ixz="0"
              iyy="${m*(x*x+z*z)/12}" iyz="0"
              izz="${m*(x*x+z*z)/12}"
    />
  </xacro:macro>

  <xacro:macro name="sphere_inertia" params="m r">
    <inertia  ixx="${2*m*r*r/5}" ixy="0" ixz="0"
              iyy="${2*m*r*r/5}" iyz="0"
              izz="${2*m*r*r/5}"
    />
  </xacro:macro>

  <!-- Macro for the wheels -->
  <xacro:macro name="wheel" params="lr tY">
    <link name="${lr}_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}"/>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
      </collision>
      <visual>
        <origin xys="0 0 0" rpy="0 ${PI/2} ${PI/2}"/>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <inertial>
        <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}"/>
        <mass value="${wheel_mass}"/>
        <cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}"/>
      </inertial>
    </link>

    <gazebo reference="${lr}_wheel">
      <mu1 value="100.0"/>
      <mu2 value="50.0"/>
      <!-- <kp value="10000000.0"/>
      <kd value="100.0"/>
      <fdir1 value="1 0 0"/> -->
      <material>Gazebo/Black</material>
    </gazebo>

    <joint name="${lr}_wheel_hinge" type="continuous">
      <type>transmission_interface/SimpleTransmission</type>
      <parent link="chassis"/>
      <child link="${lr}_wheel"/>
      <origin xyz="${-wheel_pos + chassis_length / 2} ${tY * wheel_width / 2 + tY * chassis_width / 2 + tY * 0.01} ${wheel_radius}" rpy="0 0 0"/>
      <axis xyz="0 1 0" rpy="0 0 0"/>
      <limit effort="100" velocity="100"/>
      <joint_properties damping="1.0" friciton="0.5"/>
    </joint>

    <transmission name="${lr}_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${lr}_wheel_hinge">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      </joint>
      <actuator name="${lr}_motor">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

  </xacro:macro>

</robot>
